#  makeRaster_YongCA_noQ3.R
# 
# Creates a model raster corresponding to the updated terrain values generated by the
# bayesian-updated model YongCA_noQ3.
# 
rm(list=ls())

library(raster)
IPcats <- raster("~/big_noDB/topo/terrainCats/IwahashiPike_NZ_100m_16.tif")
source("R/IP_levels.R")
source("R/MODEL_YongCA_noQ3.R")
# plot(IPcats)

YongCA_noQ3 <- IPcats
subsTable <- data.frame(groupNum = seq(1,16), newVs30 = YongCA_noQ3_lookup()$Vs30_YongCA)
YongCA_noQ3 <- subs(YongCA_noQ3, subsTable)
writeRaster(YongCA_noQ3, "~/big_noDB/models/YongCA_noQ3.tif", format="GTiff", overwrite=T)
