# This script is based on QCAMmaps_Vs30_allNZgeo_tryResample.R
#
# ALL Vs30 maps:
#   *  AhdiAK
#   *  AhdiAK_noQ3
#   *  AhdiAK_noQ3_hyb09c
#   *  AhdiAK_noQ3_hyb09c_KRG
#   *  AhdiAK_noQ3_hyb09c_MVN
#   *  YongCA
#   *  YongCA_noQ3
#   *  AhdiYongWeighted1
#   *  AhdiYongWeighted1_MVN
#   *  AhdiYongWeighted1_KRG
#   *  AhdiYongWeighted1_KRG_slopeWeighting1
#   *  AhdiYongWeighted1_MVN_slopeWeighting1
#   *  AhdiYongWeighted1_MVN_noisyT_minDist0_v2
#   *  AhdiYongWeighted1_MVN_noisyT_minDist0_v3_crp1.5
#   *  AhdiYongWeighted1_KRG_v4
#   *  AhdiYongWeighted1_KRG_v5
#   *  AhdiAK_noQ3_hyb09c_KRG_v6
#   *  YongCA_noQ3_KRG_v7
#   *  AhdiAK_noQ3_hyb09c_KRG_v8
#   *  YongCA_noQ3_KRG_v9
#   *  AhdiYongWeightedMVN


rm(list=ls())
setwd("~/VsMap")
# background rasters like hillshade etc. were generated (mostly) by R/QCAM_SCEC_GEESDV_data_allNZgeo.R
# geology maps generated by maps2.R
# Yong prior generated by Iwahashi_Pike.R
# Yong posterior not yet generated


library(raster)
source("R/MAPparams.R")
load("Rdata/vspr.Rdata")


# getVs30 points
vsprS <- subsetVsPoints(vspr)
vsSubset <- vsprS$allData


source("R/Vs30palette.R")

# random plotting stuff
nGrayCol <- 100
bgcol = rgb(1,1,1)
txtcol = rgb(0,0,0)
CEX = 3


mapIDvec <- mapIDvec_Vs30 # from MAPparams

for(region in regionVec) {
# for(region in c("CH")) {
#region <- regionVec[1]
  print(region)
  for(mapSize in mapSizeVec) {
  # for(mapSize in c("six")) { # testing
  # mapSize <- "six"
    print(mapSize)
    margins <- switch(mapSize,poster=c(7,7,7,7),three=c(2,2,2,2),six=c(2,2,2,2))
    # these are the current resampling dimensions. I chose these by measuring map pane size manually for the 
    # chosen raster output size, 3300x4200.
    rasterX <- switch(mapSize,poster=2698,three=900,six=1800)
    rasterY <- switch(mapSize,poster=3632,three=900,six=1800)
    pxWidth         = switch(mapSize,poster=3300,three=1113,six=1972)
    pxHeight        = switch(mapSize,poster=4200,three=1113,six=1972)

    hillshade        <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_hillshadeA_NZGD00.tif",rasterX,rasterY,region))
    isOcean          <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_isOcean_NZGD00.tif",rasterX,rasterY,region))
    isWater          <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_isWater_NZGD00.tif",rasterX,rasterY,region))
    isIce            <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_isIce_NZGD00.tif",rasterX,rasterY,region))
        
    for (mapID in mapIDvec) {
      print(mapID)
      
      modelRast <- raster(sprintf(switch(mapID,
                                         ## old ## AhdiAK_noQ3_hyb09c_KRG  = "~/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_AhdiAK_noQ3_hyb09c.tif",
                                         ## old ## AhdiAK_noQ3_hyb09c_MVN  = "~/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiAK_noQ3_hyb09c.tif",
                                         ## old ## AhdiYongWeighted1_KRG   = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_AhdiYongWeighted1.tif",
                                         ## old ## AhdiYongWeighted1_MVN   = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiYongWeighted1.tif",
                                         ## old ## AhdiYongWeighted1_MVN_noisyT_minDist0_v2 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiYongWeighted1_noisyT_minDist0.0km_v2.tif",
                                         ## old ## AhdiYongWeighted1_KRG_slopeWeighting1 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_AhdiYongWeighted1_KRG_slopeWeighting1_Vs30.tif",
                                         AhdiAK                  = "~/big_noDB/models/RESAMP_%04dx%04d_%s_geo_NZGD00_allNZ_AhdiAK.tif",
                                         AhdiAK_noQ3             = "~/big_noDB/models/RESAMP_%04dx%04d_%s_geo_NZGD00_allNZ_AhdiAK_noQ3.tif",
                                         AhdiAK_noQ3_hyb09c      = "~/big_noDB/models/RESAMP_%04dx%04d_%s_hyb_NZGD00_allNZ_AhdiAK_noQ3_hyb09c.tif",
                                         YongCA                  = "~/big_noDB/models/RESAMP_%04dx%04d_%s_Yong2012_Cali_Vs30.tif",
                                         YongCA_noQ3             = "~/big_noDB/models/RESAMP_%04dx%04d_%s_YongCA_noQ3.tif",
                                         AhdiYongWeighted1       = "~/big_noDB/models/RESAMP_%04dx%04d_%s_AhdiYongWeighted1.tif",
                                         AhdiYongWeighted1_MVN_slopeWeighting1 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_AhdiYongWeighted1_MVN_slopeWeighting1_Vs30.tif",
                                         AhdiYongWeighted1_MVN_noisyT_minDist0_v3_crp1.5 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiYongWeighted1_noisyT_minDist0.0km_v3_crp1.5.tif",
                                         AhdiYongWeighted1_MVN_noisyT_minDist0_v3_crp0.0 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiYongWeighted1_noisyT_minDist0.0km_v3_crp0.0.tif",
                                         AhdiYongWeighted1_MVN_noisyF_minDist0_v3_crp1.5 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiYongWeighted1_noisyF_minDist0.0km_v3_crp1.5.tif",
                                         AhdiYongWeighted1_MVN_noisyF_minDist0_v3_crp0.0 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiYongWeighted1_noisyF_minDist0.0km_v3_crp0.0.tif",
                                         AhdiYongWeighted1_KRG_v4 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_AhdiYongWeighted1_v4.tif",
                                         AhdiYongWeighted1_KRG_v5 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_AhdiYongWeighted1_v5.tif",
                                         AhdiYongWeighted1_KRG_slopeWeighting1_v5 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_AhdiYongWeighted1_KRG_slopeWeighting1_Vs30_v5.tif",
                                         AhdiAK_noQ3_hyb09c_KRG_v6    = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_AhdiAK_noQ3_hyb09c_v6.tif",
                                         YongCA_noQ3_KRG_v7           = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_YongCA_noQ3_v7.tif",
                                         AhdiAK_noQ3_hyb09c_KRG_v8    = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_AhdiAK_noQ3_hyb09c_v8.tif",
                                         YongCA_noQ3_KRG_v9           = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_KRG_Vs30_NZGD00_allNZ_YongCA_noQ3_v9.tif",
                                         AhdiAK_noQ3_hyb09c_MVN_noisyT_minDist0_v6_crp1.5 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_AhdiAK_noQ3_hyb09c_noisyT_minDist0.0km_v6_crp1.5.tif",
                                         YongCA_noQ3_MVN_noisyT_minDist0_v7_crp1.5 = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_MVN_Vs30_NZGD00_allNZ_YongCA_noQ3_noisyT_minDist0.0km_v7_crp1.5.tif",
                                         AhdiYongWeightedMVN                       = "/home/kmf76/big_noDB/models/RESAMP_%04dx%04d_%s_AhdiYongWeightedMVN_nTcrp1.5_Vs30.tif"
      ), rasterX, rasterY, region))
    
      
      
      extents <- extList[[region]]
      
      # # only plot the Vs30 points contained within in the raster extents
      coordsD <- coordinates(vsSubset)
      coX <- coordsD[,1]
      coY <- coordsD[,2]
      exM <- extents
      whichVs <- which((coX >= exM[1]) &
                         (coX <= exM[2]) &
                         (coY >= exM[3]) &
                         (coY <= exM[4]))
      vs2 <- vsSubset[whichVs,]
      vs <- vs2
      coordsD <- coordinates(vs)
      vsD <- vs$Vs30
      Dcol <- modelCol[as.numeric(cut(vsD,breaks=seq(zlims[1],zlims[2],length=nModCol+1)))] # choose colors
      
      if(mapSize=="three") {
        LARGE <- 0.6
        MED   <- 0.5
        SMALL <- 0.4 } else {
          if(mapSize=="poster" || mapSize=="six") {
            LARGE <- 1.1
            MED   <- 1
            SMALL <- 0.8
      }}
      
      sizes <- rep(LARGE, nrow(vs))
      
      q1s <- vs$QualityFlag=="Q1"
      q2s <- vs$QualityFlag=="Q2"
      q3s <- vs$QualityFlag=="Q3"
      used <- vs$QualityFlag!="Q3"
      McG <- vs$DataSource=="McGannCPT"
      Wth <- vs$DataSource=="Wotherspoon201711"
      
      sizes[q3s] <- SMALL
      sizes[q2s] <- MED
      
      shapes <- vector(length=nrow(vs))
      shapes[q1s] <- 21#23
      shapes[q2s] <- 21#22
      shapes[q3s] <- 21#21
      shapes[McG] <- 21#24
      shapes[Wth] <- 21#25
      
      
      
      fileName =  paste0("out/maps/Vs30_",region,"_",mapID,"_",mapSize,".png")
      legName  =  paste0("out/maps/Vs30_",mapSize,"_legend")
      print(fileName)
      png(fileName, width = pxWidth, height = pxHeight)
  
  
  
      # first par
      par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, bty="n")
  
      # plot hillshade first, then overlay
      plot(hillshade,
           col = grey.colors(nGrayCol, start=0, end=1), legend=F,
           xlab="NZGD2000 datum (metres)", ylab="NZGD2000 datum (metres)",
           main=switch(mapSize,three=NULL,six=NULL,poster=switch(mapID,
                              ## old ## AhdiAK_noQ3_hyb09c_KRG  = "Kriging-interpolated hybrid model: AhdiAK_noQ3_hyb09c_KRG",
                              ## old ## AhdiAK_noQ3_hyb09c_MVN  = "MVN (multivariate normal) interpolated hybrid model: AhdiAK_noQ3_hyb09c_MVN",
                              ## old ## AhdiYongWeighted1_KRG = "Kriging interpolated Vs30 model",
                              ## old ## AhdiYongWeighted1_MVN = "Multivariate normal interpolated Vs30 model: AhdiYongWeighted1_MVN",
                              ## old ## AhdiYongWeighted1_KRG_slopeWeighting1 = "Kriging interpolated Vs30 model, with slope weighting applied to interpolated model",
                              ## old ## AhdiYongWeighted1_MVN_noisyT_minDist0_v2 = "Multivariate normal interpolated Vs30 model: AhdiYongWeighted1_MVN",
                              AhdiAK = "Geology-only Vs30 model: AhdiAK",
                              AhdiAK_noQ3 = "Geology-only Vs30 model: AhdiAK_noQ3 (updated with noQ3 data)",
                              AhdiAK_noQ3_hyb09c = "Hybrid model: AhdiAK_noQ3_hyb09c",
                              YongCA = "Terrain-based model: YongCA",
                              YongCA_noQ3 = "Terrain-based model: YongCA_noQ3 (updated with noQ3 data)",
                              AhdiYongWeighted1 = "Weighted combination of AhdiAK_noQ3_hyb09c and YongCA_noQ3: AhdiYongWeighted1",
                              AhdiYongWeighted1_MVN_slopeWeighting1 = "MVN interpolated Vs30 model, with slope weighting applied to interpolated model",
                              AhdiYongWeighted1_MVN_noisyT_minDist0_v3_crp1.5 = "Multivariate normal interpolated Vs30 model: AhdiYongWeighted1_MVN (covariance reduction parameter = 1.5)",
                              AhdiYongWeighted1_MVN_noisyT_minDist0_v3_crp0.0 = "Multivariate normal interpolated Vs30 model: AhdiYongWeighted1_MVN (covariance reduction parameter = 0.0)",
                              AhdiYongWeighted1_MVN_noisyF_minDist0_v3_crp1.5 = "Multivariate normal interpolated Vs30 model: AhdiYongWeighted1_MVN (covariance reduction parameter = 1.5)",
                              AhdiYongWeighted1_MVN_noisyF_minDist0_v3_crp0.0 = "Multivariate normal interpolated Vs30 model: AhdiYongWeighted1_MVN (covariance reduction parameter = 0.0)",
                              AhdiYongWeighted1_KRG_v4 = "Kriging interpolated Vs30 model",
                              AhdiYongWeighted1_KRG_v5 = "Kriging interpolated Vs30 model",
                              AhdiYongWeighted1_KRG_slopeWeighting1_v5 = "Kriging interpolated Vs30 model, with slope weighting applied to interpolated model",
                              AhdiAK_noQ3_hyb09c_KRG_v6 = "Kriged geology-based (hybrid) model",
                              YongCA_noQ3_KRG_v7        = "Kriged terrain-based model",
                              AhdiAK_noQ3_hyb09c_KRG_v8 = "Kriged geology-based (hybrid) model",
                              YongCA_noQ3_KRG_v9        = "Kriged terrain-based model",
                              AhdiAK_noQ3_hyb09c_MVN_noisyT_minDist0_v6_crp1.5 = "Multivariate normal interpolated geology-based (hybrid) model",
                              YongCA_noQ3_MVN_noisyT_minDist0_v7_crp1.5 = "Multivariate normal interpolated terrain-based model",
                              AhdiYongWeightedMVN                       = "Final (50/50 weighted) model"
           )),
           sub=switch(mapID,
                      ## old ## AhdiYongWeighted1_MVN_noisyT_minDist0_v2 = "variogram v2  -  noise=T   -   minDist=0km",
                      AhdiAK = "Geology based on Ahdi (2017, Alaska); no bayesian updating",
                      AhdiAK_noQ3 = "Geology based on Ahdi (2017, Alaska); bayesian updating with noQ3 (all data except Kaiser Q3) NZ data",
                      AhdiAK_noQ3_hyb09c = "Hybrid model based on AhdiAK_noQ3, with slope-based modifications",
                      YongCA = "Iwahashi & Pike's (2007) terrain categories with Yong et al.'s (2012) California-based Vs30 values",
                      YongCA_noQ3 = "Iwahashi & Pike's (2007) terrain categories with Yong et al.'s (2012) California-based Vs30 values; Bayesian updating with  noQ3 (all data except Kaiser Q3 data)",
                      AhdiYongWeighted1_MVN_noisyT_minDist0_v3_crp1.5 = "variogram v3  -  noise=T   -   minDist=0km",
                      AhdiYongWeighted1_MVN_noisyT_minDist0_v3_crp0.0 = "variogram v3  -  noise=T   -   minDist=0km",
                      AhdiYongWeighted1_MVN_noisyF_minDist0_v3_crp1.5 = "variogram v3  -  noise=F   -   minDist=0km",
                      AhdiYongWeighted1_MVN_noisyF_minDist0_v3_crp0.0 = "variogram v3  -  noise=F   -   minDist=0km",
                      AhdiYongWeighted1_KRG_v4 = "variogram v4",
                      AhdiYongWeighted1_KRG_v5 = "variogram v5",
                      AhdiAK_noQ3_hyb09c_KRG_v6 = "variogram v6",
                      YongCA_noQ3_KRG_v7        = "variogram v7",
                      AhdiAK_noQ3_hyb09c_KRG_v8 = "variogram v8",
                      YongCA_noQ3_KRG_v9        = "variogram v9",
                      AhdiAK_noQ3_hyb09c_MVN_noisyT_minDist0_v6_crp1.5 = "variogram v6",
                      YongCA_noQ3_MVN_noisyT_minDist0_v7_crp1.5 = "variogram v7",
                      ""),
           cex=CEX, # cex = symbol size for scatter plots
           cex.sub = 0.8
           ,maxpixels = maxpix
           ,ext=extents
           ,axes=switch(mapSize,poster=T,three=F,six=F)
           )
  
  
  
      # map
  
      par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)
      plot(modelRast, col = modelCol, zlim=zlims,
           #xaxt=seq(from=130, to=180, by=1)*1e4, yaxt='n',
           add=T,
           alpha=0.7,
           legend=F # specify detailed legend stuff in another call.
           ,maxpixels = maxpix
           ,ext=extents
           ,axes=switch(mapSize,poster=T,three=F,six=F)
      )
      if(mapSize=="poster") { # plot as separate file for small versions
        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)
        plot(modelRast, legend.only=T,
             col=modelCol, zlim=zlims,
             legend.width=1, legend.shrink=0.75,
             axis.args=list(at    = zscale,
                            labels= zscale,
                            cex.axis=1),
             legend.args=list(text=expression('V'[s30]*'(m/s)'),
                              side=4,
                              #font=2,
                              line=3.5,
                              cex=CEX)
             ,maxpixels = maxpix
             ,ext=extents
             ,axes=switch(mapSize,poster=T,three=F)
        )
      }
  
  
      if(makeMask) {
        # add uncertainty-mask
        # must be done incrementally (not sure how to set partial alpha per pixel!)
        # There is some fine-tuning to be done with the masking. To help with this, some
        # control parameters:
        nLevels <- 10
        alphaLevelSeq <- seq(from=0, to=1, length.out=nLevels)
        alphaExp <- 1.8
        grayC <- rgb(0.8,0.8,0.8)
        for(alphaLevel in alphaLevelSeq) {
          thisMask <- MVNmask>alphaLevel
          thisMask[thisMask==0] <- NA
          par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)
          plot(thisMask, col=grayC, alpha=alphaLevel^alphaExp, add=T, legend=F)
        }
      }
  
 

      # Add water, ocean, ice
      par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)
      plot(isOcean , col = waterCol, alpha=1, add=T,  legend=F ,maxpixels = maxpix
           ,ext=extents
           ,axes=switch(mapSize,poster=T,three=F)
      )
  
      par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)
      plot(isWater , col = waterCol, alpha=1, add=T,  legend=F ,maxpixels = maxpix
           ,ext=extents
           ,axes=switch(mapSize,poster=T,three=F)
      )
  
      par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)
      plot(isIce   , col = rgb(1.0, 1.0, 1), alpha=0.8, add=T,  legend=F ,maxpixels = maxpix
           ,ext=extents
           ,axes=switch(mapSize,poster=T,three=F)
      )
  

  
      
      # plotting Vs30 points...................
  
      par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)
      
      # plot points
      # Only show Q3 points for AhdiAK geology model...
      # NAHH don't show these at all.
      #if(identical(mapID, "AhdiAK")) {
      #  points(x = coordsD[q3s,], pch=shapes[q3s], bg=Dcol[q3s], col="black", cex=sizes[q3s])}
      
      # Only plot points for the POSTERIOR models
      if(identical(mapID, "AhdiAK_noQ3_hyb09c") ||
         identical(mapID, "YongCA_noQ3")) {
           points(x = coordsD[McG,], pch=shapes[McG], bg=Dcol[McG], col="black", cex=sizes[McG])
           points(x = coordsD[Wth,], pch=shapes[Wth], bg=Dcol[Wth], col="black", cex=sizes[Wth])
           points(x = coordsD[q2s,], pch=shapes[q2s], bg=Dcol[q2s], col="black", cex=sizes[q2s])
           points(x = coordsD[q1s,], pch=shapes[q1s], bg=Dcol[q1s], col="black", cex=sizes[q1s])
      }
  
      # legend....
      # for AhdiAK, include Q3. For all other maps, don't.
      if(mapSize=="poster") {
        switch(mapID,
               AhdiAK = {
                 legend(x="topleft",
                        legend = c("Kaiser_Q1","Kaiser_Q2","Kaiser_Q3 (not used)","McGann (resampled)","Wotherspoon"),
                        pt.bg = c(modelCol[1], modelCol[22], modelCol[44], modelCol[11], modelCol[33]), # arbitrary colors
                        pch=c(23,22,21,24,25),
                        pt.cex=c(LARGE, MED, SMALL, LARGE, LARGE),
                        title = "Vs30 data: quality designation"#,
                        #horiz=T
                 )
               },
               {
                 legend(x="topleft",
                        legend = c("Kaiser_Q1","Kaiser_Q2","McGann (resampled)","Wotherspoon"),
                        pt.bg = c(modelCol[1], modelCol[22], modelCol[11], modelCol[33]), # arbitrary colors
                        pch=c(23,22,24,25),
                        pt.cex=c(LARGE, MED, LARGE, LARGE),
                        title = "Vs30 data: quality designation"#,
                        #horiz=T
                 )
               }
        )
      }

      
			# draw scale & north arrow
			if(!(publication &
			     mapID %in% c(
			       "AhdiAK",
			       "AhdiAK_noQ3_hyb09c",
			       "YongCA_noQ3",
			       "AhdiAK_noQ3_hyb09c_KRG_v6", # for two-pane kriging
			       "AhdiAK_noQ3_hyb09c_MVN_noisyT_minDist0_v6_crp1.5" # for two-pane MVN
			     ))) {
  			par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
  			drawScale(region)
  			par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
  			northarrow(region)
  		}

      dev.off()
      if(fileName=="out/maps/Vs30_CH_AhdiAK_three.png") { # just need one legend file.
                                                          # actually... two... making a taller one for the six-pane figures.
                                                          # ........... three. one more for 6-inch figures.
        for(fff in c("a","b","six")) {
          legendHeight <- switch(fff, a = pxHeight,
                                      b = pxHeight*2 + 30,
                                      six=2096)
          png(filename = switch(fff,
                                a = "out/maps/Vs30_three_legend.png",
                                b = "out/maps/Vs30_three_legendtall.png",
                                six = "out/maps/Vs30_six_legend.png"), width = 450,height = legendHeight)
          par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol)
          plot.new()
          plot(modelRast, legend.only=T,
               col=modelCol, zlim=zlims,
               legend.width=1, legend.shrink=0.75,
               axis.args=list(at    = zscale,
                              labels= zscale,
                              cex.axis=1),
               legend.args=list(text=expression('V'[s30]*'(m/s)'),
                                side=4,
                                #font=2,
                                line=3.0,
                                cex=CEX)
               ,maxpixels = maxpix
               ,ext=extents
               ,axes=switch(mapSize,poster=T,three=F)
               ,smallplot=c(0.32,0.48,0.075,0.925)
          )
          dev.off()
        }
      }
      
      
      
    } # for mapID
  } # for mapSize
} # for region
