# rasters needed for this script were generated (mostly) by R/QCAM_SCEC_GEESDV_data_allNZgeo.R
# geology category was created by AhdiGeologyCategoriesRaster.R
# terrain categories generated by Iwahashi_Pike.R
rm(list=ls())
setwd("~/VsMap/")

#library(viridis)
library(ggthemes) # use solarized
library(raster)
library(rasterVis)
source("R/functions.R")
source("R/MAP_NZGD00_regions.R") # load list of region definitions
source("R/MAPparams.R")
# iteration vectors
theSeedVec <- c(3)


mapIDvec <- mapIDvec_cats



# Vs30 points stuff......................................
load("Rdata/vspr.Rdata")
dataSubset <- "allData"  # choose which data to plot on this map
# getVs30 points
vsprS <- subsetVsPoints(vspr)
vsSubset <- vsprS[[dataSubset]]


#######################################################################################
#######################################################################################
#######################################################################################
# color and legend stuff...............................................

################################################################
###  Geology colors       ######################################
################################################################

# I need more colors than the typical schemes allow.
# see VsMap/misc/colors-max-contrast.txt
colors22 <- c(
  "#e6194b",    # Red
  "#3cb44b",    # Green
  "#ffe119",    # Yellow
  "#0082c8",    # Blue
  "#f58231",    # Orange
  "#911eb4",    # Purple
  "#46f0f0",    # Cyan
  "#f032e6",    # Magenta
  "#d2f53c",    # Lime
  "#fabebe",    # Pink
  "#008080",    # Teal
  "#e6beff",    # Lavender
  "#aa6e28",    # Brown
  # "#fffac8",    # Beige
  "#800000",    # Maroon
  "#aaffc3",    # Mint
  "#808000",    # Olive
  "#ffd8b1",    # Coral
  "#000080",    # Navy
  # "#808080",    # Grey
  # "#FFFFFF",    # White
  "#000000")    # Black


  
for(theSeed in theSeedVec) {
  # theSeed <- theSeedVec[1] # testing
  set.seed(seed = theSeed)
  geoCol <- sample(colors22, size=17, replace = F)
  
  # ice and water  - these will be colored over anyway
  geoCol[c(1,2)] <- c("#ffffff","#99e5ff")
  # modelCol <- colors22 # testing
  
  # Need to use consistent legend colors: load all-NZ map once to save lvlz.
  geoCats_allNZ_NZGD00 <- raster("~/big_noDB/models/AhdiGeoCats.tif")
  lvlz <- levels(geoCats_allNZ_NZGD00)[[1]] # store levels in data.frame
  lvlz <- lvlz[2:18,] # remove blank at beginning
  row.names(lvlz) <- NULL
  lvlz$category <- sapply(lvlz$category, FUN = function(i){paste0("G",substr(i,start=0,stop = 2))})
  
  
  ################################################################
  ###  Terrain colors       ######################################
  ################################################################
  
  source("R/IP_levels.R") # contains a single definition for I&P descriptors
  terrainCats_IP_NZGD00 <- raster("~/big_noDB/topo/terrainCats/IwahashiPike_NZ_100m_16.tif")
  levels(terrainCats_IP_NZGD00)  <- IPlevels[[1]]
  IPlevels[[1]]$category <- sapply(IPlevels[[1]]$category, FUN = function(i){paste0("T",substr(i,start=0,stop = 2))})
  
  # These colors were chosen based directly on the 4x4 legend grid used in I&P paper. Allows for direct comparison.
  terrainCol <- c("#7D4633", #1
                "#FE00FE", #2
                "#C36E2C", #3
                "#FC97CF", #4
                "#FB9600", #5
                "#FC43A6", #6
                "#FBCF66", #7
                "#FAC3D5", #8
                "#009F71", #9
                "#C4B71D", #10
                "#0072B0", #11
                "#D6D600", #12
                "#A1FD8E", #13
                "#E9E915", #14
                "#003B5B", #15
                "#F2FEBF") #16
  
  
    
    
  for(region in regionVec) {

    extents <- extList[[region]]
  
    
    # only plot the Vs30 points inside the extents box.
    coordsD <- coordinates(vsSubset)
    coX <- coordsD[,1]
    coY <- coordsD[,2]
    exM <- extents
    whichVs <- which((coX >= exM[1]) &
                       (coX <= exM[2]) &
                       (coY >= exM[3]) &
                       (coY <= exM[4]))
    vs2 <- vsSubset[whichVs,]
    vs <- vs2
    coordsD <- coordinates(vs)
  
    for(mapSize in mapSizeVec) {
      # mapSize <- mapSizeVec[1]
      
      # output
      pxWidth         = switch(mapSize, poster=3300, three=1113,six=1972) 
      pxHeight        = switch(mapSize, poster=4200, three=1113,six=1972)
      maxpix          = 1e7  # plot() for rasters is complicated. Using maxpix with massive
      # rasters doesn't NECESSARILY result in quicker plotting (1e7
      # was not working in my experience) but if raster is resampled
      # beforehand, maxpixels works as expected and doesn't cause
      # much/any delay.
      nGrayCol <- 100
      bgcol = rgb(1,1,1)
      txtcol = rgb(0,0,0)
      margins <- switch(mapSize,
                        poster = c(7,7,7,7),
                        three  = c(2,2,2,2),
                        six=c(2,2,2,2))
      # three  = c(0,0,0,0))
      CEX = switch(mapSize, poster=3, three=3)
      
      # these are the current resampling dimensions. I chose these by measuring map pane size manually for the 
      # chosen raster output size, 3300x4200. It might be slightly different with the inset legend instead of 
      # the right-side linear color scale (i.e. as used for Vs30 colorized maps), but it's close enough.
      rasterX <- switch(mapSize, poster=2698, three=900,six=1800)
      rasterY <- switch(mapSize, poster=3632, three=900,six=1800)

      # Moved all resampling to MAPresampler.R
      geoCats_allNZ_NZGD00 <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_AhdiGeoCats.tif", rasterX,rasterY,region))
      terrainCats          <- raster(sprintf("~/big_noDB/topo/terrainCats/RESAMP_%04dx%04d_%s_IwahashiPike_NZ_100m_16.tif",rasterX,rasterY,region))
      hillshade            <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_hillshadeA_NZGD00.tif",rasterX,rasterY,region))
      isOcean              <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_isOcean_NZGD00.tif",rasterX,rasterY,region))
      isWater              <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_isWater_NZGD00.tif",rasterX,rasterY,region))
      isIce                <- raster(sprintf("~/big_noDB/models/RESAMP_%04dx%04d_%s_isIce_NZGD00.tif",rasterX,rasterY,region))
      
      
    
      
    
      for(mapID in mapIDvec) {
        # mapID <- "Terrain"
        modelCol <- switch(mapID, Terrain = terrainCol,
                                    Geology = geoCol)

        
        filenameStr <- switch(mapID,
                              Terrain = "IPcats",
                              Geology = "AhdiGeoCats")
      
        # fileName = sprintf("out/maps/%s_seed%02d_%s.png",filenameStr,theSeed,region)
        fileName = sprintf("out/maps/%s_%s_%s.png", filenameStr, region, mapSize)
        legName  = sprintf("out/maps/%s_%s_legend.png", filenameStr, mapSize)
        
      
        png(fileName, width = pxWidth, height = pxHeight)
      
        # first par
        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, bty="n")#, 

        # plot hillshade first, then overlay
        plot(hillshade,
             col = grey.colors(nGrayCol, start=0, end=1), legend=F,
             xlab=switch(mapSize, poster = "NZGD2000 datum (metres)", three = NULL),
             ylab=switch(mapSize, poster = "NZGD2000 datum (metres)", three = NULL),
             main=switch(mapSize, poster = switch(mapID,
                                            Geology = "Ahdi geology categories",
                                            Terrain = "Iwahashi & Pike terrain categories"),
                                  three = NULL),
             axes=switch(mapSize,poster=T,three=F,six=F),
             # sub="some other thing"
             cex=CEX, # cex = symbol size for scatter plots
             cex.sub = 0.8
             ,maxpixels = maxpix
             ,ext=extents,
             zlim=c(1,nGrayCol)
             # ,asp=1
             )

        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T, bty="n")#,

        # Add water, ocean, ice.................
        plot(isOcean , col = waterCol, alpha=1, add=T,  legend=F ,maxpixels = maxpix
             ,ext=extents,axes=switch(mapSize,poster=T,three=F,six=F))
             # ,asp=1)

        # dev.off()

        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
        plot(isWater , col = waterCol, alpha=1, add=T,  legend=F ,maxpixels = maxpix
             ,ext=extents, axes=switch(mapSize,poster=T,three=F,six=F))

        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
        plot(isIce   , col = rgb(1.0, 1.0, 1), alpha=0.8, add=T,  legend=F ,maxpixels = maxpix
             ,ext=extents, axes=switch(mapSize,poster=T,three=F,six=F))

        # map


        modelRaster <- switch(mapID,
                              Geology = geoCats_allNZ_NZGD00,
                              Terrain = terrainCats)

        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T, bty="n")#,
        plot(modelRaster, col = modelCol,# zlim=c(1,17),
             #xaxt=switch(mapSize, poster=seq(from=130, to=180, by=1)*1e4, three='n'),
             axes=switch(mapSize,poster=T,three=F,six=F),
             add=T,
             alpha=0.5,
             legend=F # specify detailed legend stuff in another call.
             ,maxpixels = maxpix
             ,ext=extents,
             zlim=switch(mapID,
                         Geology = c(1,17),
                         Terrain = c(1,16))
             # ,asp=1
             )



        if(mapSize=="three") {
          LARGE <- 0.6
          MED   <- 0.5
          SMALL <- 0.4 } else {
            if(mapSize=="poster") {
              LARGE <- 1.1
              MED   <- 1
              SMALL <- 0.8
        }}

        #if(mapID=="Terrain") {
        if(F) { # don't plot points for terrain map
              vsD <- vs$groupID_YongCA
              Dcol <- modelCol[as.numeric(vsD)] # choose colors

              sizes <- rep(LARGE, nrow(vs))

              q1s <- vs$QualityFlag=="Q1"
              q2s <- vs$QualityFlag=="Q2"
              q3s <- vs$QualityFlag=="Q3"
              used <- vs$QualityFlag!="Q3"
              McG <- vs$DataSource=="McGannCPT"
              Wth <- vs$DataSource=="Wotherspoon201711"

              sizes[q3s] <- SMALL
              sizes[q2s] <- MED


              shapes <- vector(length=nrow(vs))
              shapes[q1s] <- 23
              shapes[q2s] <- 22
              shapes[q3s] <- 21
              shapes[McG] <- 24
              shapes[Wth] <- 25


              # plot q1 on top
              par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
              points(x = coordsD[q3s,], pch=shapes[q3s], bg=Dcol[q3s], col="black", cex=sizes[q3s])
              par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
              points(x = coordsD[q2s,], pch=shapes[q2s], bg=Dcol[q2s], col="black", cex=sizes[q2s])
              par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
              points(x = coordsD[q1s,], pch=shapes[q1s], bg=Dcol[q1s], col="black", cex=sizes[q1s])
        }

        if(mapSize=="poster") {
          par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
          legend(x="bottomright",
                 legend = switch(mapID, Geology = lvlz[3:nrow(lvlz),]$category, # no need to include ice and water
                                          Terrain = IPlevels[[1]]$category),
                 fill = switch(mapID, Geology = modelCol[3:length(modelCol)],  # no need to include ice and water
                                        Terrain = modelCol)
          )
        }
        # Vs30 point legend
        if(mapID=="Terrain" & mapSize!="three") {
            par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
            legend(x="topleft",
                   legend = c("Kaiser_Q1","Kaiser_Q2","Kaiser_Q3 (not used)","McGann (resampled)","Wotherspoon"),
                   pt.bg = c(modelCol[1], modelCol[11], modelCol[3], modelCol[2], modelCol[13]), # arbitrary colors
                   pch=c(23,22,21,24,25),
                   pt.cex=c(LARGE, MED, SMALL, LARGE, LARGE),
                   title = "Vs30 data: quality designation"#,
                   #horiz=T
            )
        }

        # draw scale & north arrow
        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
        drawScale(region)
        par(mfrow=c(1,1),  cex=CEX,   mar=margins,   bg=bgcol, col=txtcol, new=T)#,
        northarrow(region)
        
        
        
        dev.off()

        print(fileName)
        if(region=="CH" & (legName=="out/maps/IPcats_three_legend.png" |
                           legName=="out/maps/AhdiGeoCats_three_legend.png")) {
              # Only need one legend per map type.
              
              # Make a legend
              png(legName,
                  width=switch(mapID,
                                       Geology = 600,
                                       Terrain = 1200),
                  height=switch(mapID,
                                Geology = 900,
                                Terrain = 1200))
              
              # first par
              par(mfrow=c(1,1),  cex=CEX,   mar=margins,   
                  bg=bgcol, col=txtcol, bty="n")
              plot.new()
              legend(x="center",
                     legend = switch(mapID, Geology = lvlz[3:nrow(lvlz),]$category, # no need to include ice and water
                                     Terrain = IPlevels[[1]]$category),
                     fill = switch(mapID, Geology = modelCol[3:length(modelCol)],  # no need to include ice and water
                                   Terrain = modelCol)
              )
              dev.off()
              print(legName)
        }
        

      } # for mapID....
    } # for region...


  } # for(theSeed...)
} # for(mapSize...)
