# models.R
#
# all models - general functions for calling specific models
#
# the model lists are used by other functions to 
# decide which models are applicable in a given context.
# For example, the geology map processing script assigns Vs30 on a 
# per-polygon basis and therefore does not / cannot use slope.
# So items in hybMODELs are not used there.
# 
# IMPORTANT: I couldn't fully automate the assignment of model estimates
# in all scripts. Therefore, some manual updates need to be performed
# each time a new model is added.
# Do a "grep -i manually R/*" to find my notes about where this needs to be done
# (At the moment it's the following scripts/functions:
#       * processQmap.R
#       * classifyThings.R
#       * vspr.R
#       * models.R (this file)
#       * modelsUpdate.R
# )

setwd("~/VsMap")

geoMODELs <- c("AhdiAK", "YongCA")                     # Geology-only
updMODELs <- c("AhdiAK_noQ3",                          # Bayes updated models - added 20171129
               "YongCA_noQ3")                          # Bayes updated models - added 20171219
hybMODELs <- c("AhdiAK_noQ3_hyb09c")                   # hybrid models
wtdMODELs <- c("AhdiYongWeighted1")                    # weighted model(s)
allMODELs <- c(geoMODELs, updMODELs, hybMODELs, wtdMODELs)

# In the case of weighted models, for both individual vspr points (classifyThings.R, vspr.R), 
# AND for rasters (makeRaster_AhdiYongWeighted1.R, makeRaster_AhdiYongWeighted1_sigma.R),
# the weighted Vs30 and sigma estimates are generated by log averaging and square root of sum of squares.
# There is no need for a unique MODEL_AhdiYongWeighted1.R. So I have removed that file and 
# don't need to source it below.
allMODELsButWtd <- c(geoMODELs, updMODELs, hybMODELs)

for(theModelJustForThisLoop in allMODELsButWtd) {
  source(paste0("R/MODEL_",theModelJustForThisLoop,".R"))
}
