# modelsUpdate.R
#
# this script performs Bayesian updating on selected models and datasets.
# It generates detailed text tables for debugging.
# The resulting updated models are used by table lookup by another function. (byaesPosteriors.R)
# 
# 
# To avoid mistakenly overwriting models when experimenting 
# with new parameters, the tables are manually renamed for later
# reference and for access by MODEL_xxxx.R files.
# 
#  Model update log:
# 
#    Date       Notes
#  201708       nObsPrior = 3 ; measPrecision = 1 ; minSigma = 0.5
#  20171129     Added noQ3 and noQ3noMcGann
#  
rm(list=ls())
setwd("~/VsMap")

# parameters:
nObsPrior     = 3 # how many observations are represented by the prior model? this is subjective.
measPrecision = 1 # 0 for perfect precision; 1 for taking measUncer directly from datasource. 
minSigma      = 0.5 # enfore a minimum value of sigma in the prior for each model.

source("R/bayes.R")
source("R/functions.R")
source("R/models.R")

library(knitr)

load("Rdata/vspr.Rdata")
vsprSubsets <- subsetVsPoints(vspr)

dataStrList <- c("Kaiser_noQ3", "Kaiser_all", 
                 "noQ3", "noQ3noMcGann")
mList <- c("AhdiAK", "YongCA")


for (dataStr in dataStrList) {
  # dataStr <- dataStrList[1] # testing
  for (MODEL in mList) {
    # MODEL <- mList[1] # testing
    paramStr <- sprintf("DATA_%s__nObsPrior%03d_measPrec%1d_minSigma%0.3f.txt",
                        dataStr,nObsPrior,measPrecision,minSigma)
    
    data  = vsprSubsets[[dataStr]]
    groupIDmod <- switch(MODEL,     AhdiAK = AhdiAK_lookup()$groupID,        YongCA = YongCA_lookup()$groupID)
    groupIDobs <- switch(MODEL,     AhdiAK = data$groupID_AhdiAK,            YongCA = data$groupID_YongCA)
    Vs30mod    <- switch(MODEL,     AhdiAK = AhdiAK_lookup()$Vs30_AhdiAK,    YongCA = YongCA_lookup()$Vs30_YongCA)
    stDvMod    <- switch(MODEL,     AhdiAK = AhdiAK_lookup()$stDv_AhdiAK,    YongCA = YongCA_lookup()$stDv_YongCA)
    upd <- bayesPosterior(data, groupIDmod, groupIDobs, Vs30mod,  stDvMod)
    
    sink(paste0("out/bayesUpdateSummary_NinvChiSq_",paramStr),append = F)
    cat("This summary generated by R/modelsUpdate.R.\n\n")
    
    cat("## MODEL:  ",MODEL, "###############################################################################################\n")
    cat("This updating assumes every geology group consists of ", nObsPrior, " previous observations (i.e. the Ahdi dataset has ", nObsPrior, " observations in each group.\n\n")
    print(knitr::kable(upd$summary, digits=3), row.names = F)
    cat("\n\n\n\n\n")
    
    for(i in 1:length(upd$byGroup)) {
      cat(paste0(" GROUP:     ",upd$summary$groupID[i], "  (", 
                 upd$summary$nObs[i], " observations) ..."))
      print(knitr::kable(upd$byGroup[[i]], digits=3), row.names = F)
      cat("\n\n\n")
    }
    
    sink()
    
    updateDataName <- switch(MODEL,
                             AhdiAK = switch(dataStr,
                                             Kaiser_noQ3   =  "upd_AhdiAK_KaiNoQ3",
                                             Kaiser_all    =  "upd_AhdiAK_KaiAll",
                                             noQ3          =  "upd_AhdiAK_noQ3",
                                             noQ3noMcGann  =  "upd_AhdiAK_noQ3noMcGann"),
                             YongCA = switch(dataStr,
                                             Kaiser_noQ3   =  "upd_YongCA_KaiNoQ3",
                                             Kaiser_all    =  "upd_YongCA_KaiAll",
                                             noQ3          =  "upd_YongCA_noQ3",
                                             noQ3noMcGann  =  "upd_YongCA_noQ3noMcGann"))
    assign(updateDataName, upd)
  }
}

######################################
#### SAVE RESULTING TABLES ###########
######################################

# These must be loaded along with helper functions for model
# lookups by classifyThings() in order to generate
# residuals that can be automatically plotted in plots1.R and analysisKF.R

save(upd_AhdiAK_KaiNoQ3,
     upd_AhdiAK_KaiAll, 
     upd_AhdiAK_noQ3noMcGann,   # added 20171129
     upd_AhdiAK_noQ3,           # added 20171129
     upd_YongCA_noQ3,           # added 20171218
     file = "Rdata/BayesUpdateTables.Rdata")
